openapi: 3.2.0
info:
  title: api-partners Applications API
  description: 'Change log:


    1.4.0 (2026-06-01)


    Signals: Added productType field to Signal response of GET /applicants/{partnerApplicantId}/signals.'
  version: 1.4.0
servers:
- url: https://dev.weareuncapped.com/api/partners
  description: Sandbox server
- url: https://portal.weareuncapped.com/api/partners
  description: Production server
security:
- auth0_bearer:
  - read
  - write
tags:
- name: Applications
  description: Application API for external access
paths:
  /applications/{applicationId}:
    get:
      tags:
      - Applications
      summary: Get application details
      description: Retrieves application details by application ID. Requires trusted or partner authorization.
      operationId: getApplication
      parameters:
      - name: applicationId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Application successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExternalApplicationDetailsResponse'
        '404':
          description: Application not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ApplicantUserDetails:
      type: object
      properties:
        id:
          type: string
    ExternalApplicationDetailsResponse:
      type: object
      properties:
        id:
          type: string
        status:
          type: string
          enum:
          - CREATED
          - STARTED
          - APPROVED
          - REJECTED
          - ACTIVE
          - CLOSED
          - ABANDONED
        partnerApplicantId:
          type: string
        estimationId:
          type: string
        applicantUsers:
          type: array
          items:
            $ref: '#/components/schemas/ApplicantUserDetails'
    CodeMessage:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        fieldName:
          type: string
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        code:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/CodeMessage'
  securitySchemes:
    auth0_bearer:
      type: http
      name: authorization
      scheme: bearer
      bearerFormat: JWT
