openapi: 3.2.0
info:
  title: api-partners Authentication API
  description: 'Change log:


    1.4.0 (2026-06-01)


    Signals: Added productType field to Signal response of GET /applicants/{partnerApplicantId}/signals.'
  version: 1.4.0
servers:
- url: https://dev.weareuncapped.com/api/partners
  description: Sandbox server
- url: https://portal.weareuncapped.com/api/partners
  description: Production server
security:
- auth0_bearer:
  - read
  - write
tags:
- name: Authentication
  description: Authentication API for external access
paths:
  /partner/authentication/token:
    post:
      tags:
      - Authentication
      summary: Issue access token
      description: Authenticates the partner using the provided JWT token and issues an access token. The access token can be used in the Authorization header as 'Bearer {accessToken}' for subsequent API calls.
      operationId: issueAccessToken
      requestBody:
        description: JWT token containing client id
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRequest'
        required: true
      responses:
        '200':
          description: Successfully authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Bad Request - Missing body or invalid JSON
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    TokenResponse:
      type: object
      properties:
        accessToken:
          type: string
          minLength: 1
      required:
      - accessToken
    CodeMessage:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        fieldName:
          type: string
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        code:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/CodeMessage'
    TokenRequest:
      type: object
      properties:
        token:
          type: string
          minLength: 1
      required:
      - token
  securitySchemes:
    auth0_bearer:
      type: http
      name: authorization
      scheme: bearer
      bearerFormat: JWT
